### ISSUE TITLE
Stop using whitelist / blacklist terms

### ISSUE THREAD

**Issue by hkdobrev** [EnergizedProtection/block#475]
Could you please change the terminology to use allow list and deny list instead of the whitelist / blacklist terms?

The problem with the old terms is they implicitly infer "white" is related to good and proper and "black" is related to bad and dangerous.

Prior art with more info and context:

- https://github.com/rails/rails/issues/33677
- https://www.zdnet.com/article/uk-ncsc-to-stop-using-whitelist-and-blacklist-due-to-racial-stereotyping/

**Comment by foray1010** [comment]
Should we rename yellow fever, black death, black market and many others too?

If the word doesn't mean to offense people, **it is okay**. I do not want to live in a world where everyone have to double check every single word they said just to make sure everything is perfectly political correct.

**Comment by badmojr** [comment]
😝😂

**Comment by hkdobrev** [comment]
Using any colour to refer to a colour is completely fine. When using a colour to refer to a preconceived good/bad analogy based on colors is the problem.

It's completely up to you whether you'd do or not do that. I'm raising it as a concern as it's a concern for many people around the world and technology has its part in it. Take a look at some of the other examples and decide for yourself.

It's up to you.

**Comment by badmojr** [comment]
While we are at it,
Let’s get rid of traffic lights too..

**Comment by badmojr** [comment]
Fool,
Black is beautiful...
It’s your black heart that isn’t.

**Comment by hkdobrev** [comment]
Here's a good thread from today: https://twitter.com/s_bergmann/status/1269917026107248641

Not only the suggested terms like exclude list or deny list do not have such negative connotations, but many agree they are also more clear and explicit.

I'm going to stop commenting here as I see my comments somehow incite hate and ridicule. Feel free to either implement the change or close and lock the issue.

Thanks!

**Comment by badmojr** [comment]
@AdroitAdorKhan @AvinashReddy3108 
what’s your take on this?

**Comment by AdroitAdorKhan** [comment]
@badmojr I have been checking this thread silently. But if you say which side I would pick, I would love to go with @foray1010 . Does naming a simple text list black/white really matter?! Seriously?!

But this is still the community project, if people think we should change them to allow/deny/block lists, I would happily do that. But it's sad to see this type of changing here in this community too! 

If you count black or white, I will be in the black-list too! Does it make me bad? Do I not work for this project, just because of being a black-listed guy? Do white ones in our team feel better being in white-list?! No, right?! 
Man we want a simple world, don't make it too much complicated.

**Comment by blacklistisnotracist** [comment]
I do agree terms like allowlist/blocklist may be better because they are more descriptive. That being said, calling blacklist or whitelist a racist word is simply wrong.

First, blacklist's origins have nothing to do with black people. What's more, it has never been used as an abusive word against black people. It's only a certain group of extreme non-black liberals who find the word offensive and try to make them look like it has racist connotations. It's as ridiculous as people who think [wearing Chinese clothes is offensive for Chinese people unless they are worn by Chinese people](https://www.youtube.com/watch?v=GNXm7juuM-8).

Black, as a color, carries negative connotations across many cultures. It's so embedded that hunting down every word from every language is almost impossible and meaningless.

Let's stop calling a group of people black first. Let's start from there. Color comes first. Race came later. Colors are tied to images, which can't be changed. We shouldn't be tying a race with a color in the first place.

Let's stop the hypocrisy and focus on something that have real impacts.
